@file:Suppress("HasPlatformType")

package me.ashypinguin.atvsrg.utils

import com.badlogic.gdx.graphics.Color.*

val LEFT_COLOR = YELLOW
val LEFT_MID_COLOR = ORANGE
val RIGHT_MID_COLOR = RED
val RIGHT_COLOR = PURPLE

val LEFT_COLUMN_COLOR = LEFT_COLOR.dull(COLUMN_DARKNESS)
val LEFT_MID_COLUMN_COLOR = LEFT_MID_COLOR.dull(COLUMN_DARKNESS)
val RIGHT_MID_COLUMN_COLOR = RIGHT_MID_COLOR.dull(COLUMN_DARKNESS)
val RIGHT_COLUMN_COLOR = RIGHT_COLOR.dull(COLUMN_DARKNESS)

val LEFT_UNPRESSED_COLOR = LEFT_COLOR.dull(KEY_UNPRESSED_DARKNESS)
val LEFT_MID_UNPRESSED_COLOR = LEFT_MID_COLOR.dull(KEY_UNPRESSED_DARKNESS)
val RIGHT_MID_UNPRESSED_COLOR = RIGHT_MID_COLOR.dull(KEY_UNPRESSED_DARKNESS)
val RIGHT_UNPRESSED_COLOR = RIGHT_COLOR.dull(KEY_UNPRESSED_DARKNESS)

val LEFT_NOTE_COLOR = LEFT_COLOR.dull(NOTE_DARKNESS)
val LEFT_MID_NOTE_COLOR = LEFT_MID_COLOR.dull(NOTE_DARKNESS)
val RIGHT_MID_NOTE_COLOR = RIGHT_MID_COLOR.dull(NOTE_DARKNESS)
val RIGHT_NOTE_COLOR = RIGHT_COLOR.dull(NOTE_DARKNESS)

val RHYTHM_BAR_COLOR = LIGHT_GRAY
val UI_ELEMENT_BG_COLOR = DARK_GRAY
val DRAWABLE_BG_COLOR = BLACK

val RANK_SS_COLOR = GOLD
val RANK_S_COLOR = LIGHT_GRAY
val RANK_A_COLOR = LIME

fun Int.offsetToColor() = when (this) {
  0 -> LEFT_COLOR
  1 -> LEFT_MID_COLOR
  2 -> RIGHT_MID_COLOR
  3 -> RIGHT_COLOR
  else -> throw IllegalArgumentException("Unexpected key index $this")
}

fun Int.offsetToUnpressedColor() = when (this) {
  0 -> LEFT_UNPRESSED_COLOR
  1 -> LEFT_MID_UNPRESSED_COLOR
  2 -> RIGHT_MID_UNPRESSED_COLOR
  3 -> RIGHT_UNPRESSED_COLOR
  else -> throw IllegalArgumentException("Unexpected key index $this")
}
