package me.ashypinguin.atvsrg.utils

import com.badlogic.gdx.graphics.Color

val LEFT_COLOR = Color.YELLOW!!
val LEFT_MID_COLOR = Color.ORANGE!!
val RIGHT_MID_COLOR = Color.RED!!
val RIGHT_COLOR = Color.PURPLE!!

val LEFT_COLUMN_COLOR = LEFT_COLOR.dull(COLUMN_DARKNESS)
val LEFT_MID_COLUMN_COLOR = LEFT_MID_COLOR.dull(COLUMN_DARKNESS)
val RIGHT_MID_COLUMN_COLOR = RIGHT_MID_COLOR.dull(COLUMN_DARKNESS)
val RIGHT_COLUMN_COLOR = RIGHT_COLOR.dull(COLUMN_DARKNESS)

val LEFT_UNPRESSED_COLOR = LEFT_COLOR.dull(KEY_UNPRESSED_DARKNESS)
val LEFT_MID_UNPRESSED_COLOR = LEFT_MID_COLOR.dull(KEY_UNPRESSED_DARKNESS)
val RIGHT_MID_UNPRESSED_COLOR = RIGHT_MID_COLOR.dull(KEY_UNPRESSED_DARKNESS)
val RIGHT_UNPRESSED_COLOR = RIGHT_COLOR.dull(KEY_UNPRESSED_DARKNESS)

val LEFT_NOTE_COLOR = LEFT_COLOR.dull(NOTE_DARKNESS)
val LEFT_MID_NOTE_COLOR = LEFT_MID_COLOR.dull(NOTE_DARKNESS)
val RIGHT_MID_NOTE_COLOR = RIGHT_MID_COLOR.dull(NOTE_DARKNESS)
val RIGHT_NOTE_COLOR = RIGHT_COLOR.dull(NOTE_DARKNESS)

val RHYTHM_BAR_COLOR = Color.LIGHT_GRAY!!

fun Int.offsetToColor() = when (this) {
  0 -> LEFT_COLOR
  1 -> LEFT_MID_COLOR
  2 -> RIGHT_MID_COLOR
  3 -> RIGHT_COLOR
  else -> throw IllegalArgumentException("Unexpected key index $this")
}

fun Int.offsetToUnpressedColor() = when (this) {
  0 -> LEFT_UNPRESSED_COLOR
  1 -> LEFT_MID_UNPRESSED_COLOR
  2 -> RIGHT_MID_UNPRESSED_COLOR
  3 -> RIGHT_UNPRESSED_COLOR
  else -> throw IllegalArgumentException("Unexpected key index $this")
}
